stages:
  - build
  - deploy
  - cleanup

include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: 'hive/common-ci-configuration'
    ref: c9cb02ea67f9f381f52280be4ca1f708243373a0
    file:
      - '/templates/docker_image_jobs.gitlab-ci.yml'
      - '/templates/npm_projects.gitlab-ci.yml'

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

default:
  tags:
    - public-runner-docker

.content_path_evaluator:
  extends: .job-defaults
  rules:
    # default branch is exposed at GitLab Pages root
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      variables:
        # subpath to ephemeral branches content for preview
        CURRENT_CONTENT_PATH: "preview/$CI_COMMIT_REF_SLUG"
    - variables:
        CURRENT_CONTENT_PATH: "." # default subdir for main branch (be overrided for others)

build4pages:
  extends:
    - .npm_based_job_base
    - .content_path_evaluator

  stage: build
  script: |
    set -xe
    export NUXT_APP_BASE_URL="/$CURRENT_CONTENT_PATH/"
    echo "App base url used for generation $NUXT_APP_BASE_URL"
    pnpm generate

  artifacts:
    paths:
      - .output
    when: always
    expire_in: 1 week

build:
  extends:
    - .npm_based_job_base

  stage: build
  script:
    - pnpm build

  artifacts:
    paths:
      - .output
    when: always
    expire_in: 1 week

.build_app_image_base:
  extends: .docker_image_builder_job_template
  stage: deploy

  needs:
    - job: build
      artifacts: true

  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_DEPTH: 1
    IMAGE_TAG: ""
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - ./scripts/ci-helpers/build_instance.sh --push "$IMAGE_TAG" "$CI_PROJECT_DIR" "$CI_REGISTRY_IMAGE" --progress="plain"

  artifacts:
    reports:
      dotenv: app_docker_image_name.env

build_app_image:
  extends: .build_app_image_base

  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"

push_protected_app_image:
  extends: .build_app_image_base
  stage: deploy
  variables:
    IMAGE_TAG: "$CI_COMMIT_REF_NAME"
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
      when: on_success
    - when: never

.pages_deployment_base:
  extends: .content_path_evaluator
  stage: deploy

  cache:
    key: gitlab-pages
    paths: [public]

  artifacts:
    paths: [public]

pages:
  extends: .pages_deployment_base

  needs:
    - job: build4pages
      artifacts: true

  script:
    - echo "App specific directory used for gitlab pages publishing $CURRENT_CONTENT_PATH"
    - rm -vrf public/$CURRENT_CONTENT_PATH/* # remove last version of current branch
    - mkdir -vp public/$CURRENT_CONTENT_PATH
    - mv .output/public/* public/$CURRENT_CONTENT_PATH
    - echo "App instance will be available at $CI_PAGES_URL/$CURRENT_CONTENT_PATH" or through Operate/Environments view by pointing "pages/$CI_COMMIT_REF_SLUG"

  environment:
    name: "pages/$CI_COMMIT_REF_SLUG"
    action: start
    url: $CI_PAGES_URL/$CURRENT_CONTENT_PATH
    on_stop: pages-clean-preview


pages-clean-preview:
  extends: .pages_deployment_base
  script:
    - rm -vrf public/$CURRENT_CONTENT_PATH/*
  environment:
    name: "pages/$CI_COMMIT_REF_SLUG"
    action: stop

  when: manual
  allow_failure: true

deploy_prod_environment:
  extends: .webapp_deploy_template
  stage: deploy
  needs:
    - push_protected_app_image
  variables:
    IMAGE_NAME: "${APP_IMAGE_NAME}"
    CONTAINER_NAME: "txi_prod_deployment"
    PORT: 5555 # tx.openhive.network (mainnet)(port 5555)
    DEPLOYMENT_ENV_FILE: "MAINNET_PROD_DEPLOYMENT_ENV"
  environment:
    name: txi-prod-mainnet
    url: https://auth.openhive.network
    on_stop: stop_prod_environment

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "bw_fix_ci" && $CI_COMMIT_REF_PROTECTED == "true"'
      when: on_success
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: on_success
    - when: never

stop_prod_environment:
  extends: .webapp_stop_template
  stage: cleanup
  needs:
  - job: deploy_prod_environment
    optional: true
  variables:
    CONTAINER_NAME: txi_prod_deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == "bw_fix_ci" && $CI_COMMIT_REF_PROTECTED == "true"'
      when: manual
      allow_failure: true
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: manual
      allow_failure: true
  environment:
    name: txi-prod-mainnet
    action: stop